#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementMVCLinq.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StudentDb")]
	public partial class StudentClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    #endregion
		
		public StudentClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StudentDbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studId;
		
		private string _studFirstName;
		
		private string _studLastName;
		
		private int _studYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudIdChanging(int value);
    partial void OnstudIdChanged();
    partial void OnstudFirstNameChanging(string value);
    partial void OnstudFirstNameChanged();
    partial void OnstudLastNameChanging(string value);
    partial void OnstudLastNameChanged();
    partial void OnstudYearChanging(int value);
    partial void OnstudYearChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int studId
		{
			get
			{
				return this._studId;
			}
			set
			{
				if ((this._studId != value))
				{
					this.OnstudIdChanging(value);
					this.SendPropertyChanging();
					this._studId = value;
					this.SendPropertyChanged("studId");
					this.OnstudIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studFirstName", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string studFirstName
		{
			get
			{
				return this._studFirstName;
			}
			set
			{
				if ((this._studFirstName != value))
				{
					this.OnstudFirstNameChanging(value);
					this.SendPropertyChanging();
					this._studFirstName = value;
					this.SendPropertyChanged("studFirstName");
					this.OnstudFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studLastName", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string studLastName
		{
			get
			{
				return this._studLastName;
			}
			set
			{
				if ((this._studLastName != value))
				{
					this.OnstudLastNameChanging(value);
					this.SendPropertyChanging();
					this._studLastName = value;
					this.SendPropertyChanged("studLastName");
					this.OnstudLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studYear", DbType="Int NOT NULL")]
		public int studYear
		{
			get
			{
				return this._studYear;
			}
			set
			{
				if ((this._studYear != value))
				{
					this.OnstudYearChanging(value);
					this.SendPropertyChanging();
					this._studYear = value;
					this.SendPropertyChanged("studYear");
					this.OnstudYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
